name: Playwright Tests

on:
  push:
    branches: [ main, UI_API_Test ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      
      - name: Build & Install
        run: mvn -B install -D skipTests --no-transfer-progress
      
      - name: Install Playwright
        run: mvn exec:java -e -D exec.mainClass=com.microsoft.playwright.CLI -D exec.args="install --with-deps"
      
      - name: Run tests
        run: xvfb-run --auto-servernum mvn test
      
      - name: Debug - Check Maven build output
        run: |
          echo "Checking target directory:"
          ls -R target
          echo "Checking surefire-reports:"
          cat target/surefire-reports/*.txt
        continue-on-error: true

      - name: Debug - List contents of target directory
        run: ls -R target
        shell: bash

      - name: Debug - Check Allure results existence
        run: |
          if [ -d "target/allure-results" ]; then
            echo "Allure results directory found."
            ls -R target/allure-results
          else
            echo "Allure results directory NOT found."
            echo "Checking other possible locations:"
            ls -R target
          fi
        shell: bash

      - name: Upload Log Files
        uses: actions/upload-artifact@v3
        with:
          name: test-logs
          path: src/test/resources/Log/*.log

      # Step to retrieve Allure history from the gh-pages branches
      - name: Get Allure history from gh-pages
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install Allure Commandline
        run: npm install -g allure-commandline

      - name: Generate Allure Report
        run: |
          echo "Allure CommandLine version:"
          allure --version
          echo "Checking target/allure-results directory:"
          ls -R target/allure-results || echo "target/allure-results not found"
          echo "Generating Allure report..."
          allure generate target/allure-results --clean -o allure-report || echo "Allure report generation failed"
          echo "Checking generated report directory:"
          ls -R allure-report || echo "allure-report directory not found"
        continue-on-error: true

      - name: Debug - Check Allure Results Content
        run: |
          echo "Checking content of allure-results directory:"
          find . -name "allure-results" -type d -exec ls -R {} \;
        continue-on-error: true

      - name: Deploy Allure report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-report
          force_orphan: true

      - name: Check GitHub Pages Status
        run: |
          echo "Checking GitHub Pages deployment status..."
          status_url=$(curl -s -I "https://${GITHUB_REPOSITORY_OWNER}.github.io/${GITHUB_REPOSITORY#*/}/" | grep -i "^location:" | awk '{print $2}' | tr -d '\r')
          echo "GitHub Pages URL: $status_url"
          if [[ $status_url == *"/404.html" ]]; then
            echo "GitHub Pages not deployed yet or encountering issues."
          else
            echo "GitHub Pages seems to be deployed successfully."
          fi
        continue-on-error: true

      - name: Upload Allure Report
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: target/site/allure-maven-plugin
